# Generated by Django 4.2.16 on 2024-10-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='carte_etudiant',
            field=models.ImageField(blank=True, null=True, upload_to='barrecode/'),
        ),
    ]
