# Generated by Django 4.2.16 on 2024-10-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0003_alter_etudiant_carte_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], default='L1', max_length=20),
            preserve_default=False,
        ),
    ]
