# Generated by Django 4.2.16 on 2024-11-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0005_remove_enseignant_id_remove_etudiant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsablepedagogique',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.utilisateur'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.utilisateur'),
        ),
        migrations.AlterField(
            model_name='responsablepedagogique',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.utilisateur'),
        ),
    ]
