# Generated by Django 4.2.16 on 2024-10-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
                ('fprint', models.BinaryField()),
                ('codebar', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
