# Generated by Django 4.2.16 on 2024-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseigner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseigner',
            name='etudiants',
        ),
        migrations.AddField(
            model_name='enseigner',
            name='niveau',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], default='L1', max_length=20),
            preserve_default=False,
        ),
    ]
