# Generated by Django 4.2.16 on 2024-11-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0005_remove_enseignant_id_remove_etudiant_id_and_more'),
        ('enseigner', '0004_alter_enseigner_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigner',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.etudiant'),
        ),
    ]
