# Generated by Django 4.2.16 on 2024-11-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0006_enseignant_id_etudiant_id_responsablepedagogique_id_and_more'),
        ('enseigner', '0005_alter_enseigner_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigner',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.enseignant'),
        ),
    ]
